version: '3.7'

services:

  php-order-api:
    image: order-api-php:0.0.1
    depends_on:
      - rabbitmq
    ports:
      - 8000:80

  php-voucher-event-listener:
    image: voucher-event-listener:0.0.1
    depends_on:
      - rabbitmq
    restart: on-failure

  php-voucher-api:
    image: voucher-api-php:0.0.1
    depends_on:
      - rabbitmq
    ports:
      - 8001:80

  mysql-real-order:
    image: order-mysql:0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: GCECjdRLf7RvwJLJ
    volumes:
      - real-order-data:/var/lib/mysql

  mysql-real-voucher:
    image: voucher-mysql:0.0.1
    environment:
      MYSQL_ROOT_PASSWORD: GCECjdRLf7RvwJLJ
    volumes:
      - real-voucher-data:/var/lib/mysql

  phpmyadmin-real:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: mysql-real-order,mysql-real-voucher
      PMA_PASSWORD: GCECjdRLf7RvwJLJ
      PMA_USER: root
    ports:
      - "81:80"
    depends_on:
      - mysql-real-order
      - mysql-real-voucher

  rabbitmq:
    image: order-voucher-rabbitmq:0.0.1
    ports:
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'

volumes:
  real-order-data:
#    external:
#      name: real-db-order
  real-voucher-data:
#    external:
#      name: real-db-voucher
  rabbitmq_data:
