FROM mysql:5.6 AS development

FROM development AS order-mysql

COPY docker/db/order /docker-entrypoint-initdb.d

CMD ["mysqld"]

FROM development AS voucher-mysql

COPY docker/db/voucher /docker-entrypoint-initdb.d

CMD ["mysqld"]